from app import db

"""
    Represents a category for skills within the application.

    Each category can have multiple skills associated with it. The relationship
    between Category and Skill is defined such that each skill belongs to one category.

    Attributes:
        __tablename__ (str): The name of the table in the database, set to 'category'.
        id (int): The primary key for the category, automatically generated by the database.
        name (str): The name of the category. This field is not nullable.
        color (str): The color associated with the category, used for UI display purposes. This field is not nullable.
        skills (SQLAlchemy relationship): A dynamic relationship that provides access to the skills associated with this category.
            This is set to be a dynamic loader, meaning it does not load the skills until accessed, allowing for more efficient queries
            on categories without immediately loading all related skills.
"""

class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    color = db.Column(db.String, nullable=False)
    skills = db.relationship('Skill', backref='category', lazy='dynamic')