from app import db
#from app.models.Category import Category

"""
    Represents a specific skill that can be associated with a category.

    Each skill is linked to one category through a foreign key relationship, 
    reflecting a many-to-one relationship where each skill belongs to one category 
    defined in the Category class.

    Attributes:
        __tablename__ (str): The name of the table in the database, set to 'skill'.
        id (int): The primary key for the skill, automatically generated by the database.
        name (str): The name of the skill. This field is not nullable, ensuring every skill must have a name.
        category_id (int): The foreign key linking this skill to its respective category.
            This field references 'category.id', ensuring database integrity by linking to an existing category.
"""

class Skill(db.Model):
    __tablename__ = 'skill'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
    
    #category = db.relationship('Category', back_populates='skill')